// Mocks generated by Mockito 5.4.6 from annotations
// in pet_finder_app/test/features/home/data/datasources/breed_remote_data_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pet_finder_app/core/api/api_consumer.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ApiConsumer].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiConsumer extends _i1.Mock implements _i2.ApiConsumer {
  MockApiConsumer() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> get({
    required String? path,
    _i4.Options? options,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#get, [], {
              #path: path,
              #options: options,
              #queryParameters: queryParameters,
            }),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> post({
    required String? path,
    Object? body,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#post, [], {
              #path: path,
              #body: body,
              #queryParameters: queryParameters,
            }),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> put({
    required String? path,
    Map<String, dynamic>? body,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#put, [], {
              #path: path,
              #body: body,
              #queryParameters: queryParameters,
            }),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> delete({
    required String? path,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #path: path,
              #queryParameters: queryParameters,
            }),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);

  @override
  _i3.Future<dynamic> patch({
    required String? path,
    Map<String, dynamic>? body,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#patch, [], {
              #path: path,
              #body: body,
              #queryParameters: queryParameters,
            }),
            returnValue: _i3.Future<dynamic>.value(),
          )
          as _i3.Future<dynamic>);
}
