// Mocks generated by Mockito 5.4.6 from annotations
// in pet_finder_app/test/features/home/presentation/widgets/categories_widget_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:bloc/bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:pet_finder_app/features/home/data/models/breed_model.dart'
    as _i6;
import 'package:pet_finder_app/features/home/data/models/category_model.dart'
    as _i5;
import 'package:pet_finder_app/features/home/data/repositories/breed_repository.dart'
    as _i3;
import 'package:pet_finder_app/features/home/data/repositories/category_repository.dart'
    as _i2;
import 'package:pet_finder_app/features/home/presentation/cubit/home_cubit.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeCategoryRepository_0 extends _i1.SmartFake
    implements _i2.CategoryRepository {
  _FakeCategoryRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBreedRepository_1 extends _i1.SmartFake
    implements _i3.BreedRepository {
  _FakeBreedRepository_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHomeState_2 extends _i1.SmartFake implements _i4.HomeState {
  _FakeHomeState_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeCubit extends _i1.Mock implements _i4.HomeCubit {
  MockHomeCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CategoryRepository get categoryRepository =>
      (super.noSuchMethod(
            Invocation.getter(#categoryRepository),
            returnValue: _FakeCategoryRepository_0(
              this,
              Invocation.getter(#categoryRepository),
            ),
          )
          as _i2.CategoryRepository);

  @override
  _i3.BreedRepository get breedRepository =>
      (super.noSuchMethod(
            Invocation.getter(#breedRepository),
            returnValue: _FakeBreedRepository_1(
              this,
              Invocation.getter(#breedRepository),
            ),
          )
          as _i3.BreedRepository);

  @override
  List<_i5.CategoryModel> get categoriesData =>
      (super.noSuchMethod(
            Invocation.getter(#categoriesData),
            returnValue: <_i5.CategoryModel>[],
          )
          as List<_i5.CategoryModel>);

  @override
  List<_i6.BreedModel> get breedsData =>
      (super.noSuchMethod(
            Invocation.getter(#breedsData),
            returnValue: <_i6.BreedModel>[],
          )
          as List<_i6.BreedModel>);

  @override
  set categoriesData(List<_i5.CategoryModel>? _categoriesData) =>
      super.noSuchMethod(
        Invocation.setter(#categoriesData, _categoriesData),
        returnValueForMissingStub: null,
      );

  @override
  set breedsData(List<_i6.BreedModel>? _breedsData) => super.noSuchMethod(
    Invocation.setter(#breedsData, _breedsData),
    returnValueForMissingStub: null,
  );

  @override
  _i4.HomeState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeHomeState_2(this, Invocation.getter(#state)),
          )
          as _i4.HomeState);

  @override
  _i7.Stream<_i4.HomeState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i7.Stream<_i4.HomeState>.empty(),
          )
          as _i7.Stream<_i4.HomeState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i7.Future<void> getCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getCategories, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> getBreeds({int? limit = 10, int? page = 0}) =>
      (super.noSuchMethod(
            Invocation.method(#getBreeds, [], {#limit: limit, #page: page}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  void emit(_i4.HomeState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i4.HomeState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
